services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["./wait-for-it.sh", "mysql_server:3306", "--", "./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "start"]
    depends_on:
      - mysql_server
      - rabbitmq

  mysql_server:
    image: mysql:latest
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"